eurofurence/ef-app_backend-dotnet-core

- docker-compose.yml
- justfile
- src/Eurofurence.App.Server.Web/appsettings.sample.json
Added a MinIO container to the `docker-compose.yml` for local testing. To verify, run `just clean; just containerize; just up` in the root of the repo and wait until `minio-init` has completed (might take a few seconds).
If `just` is unavailable, try running the following in the root of the repo:
```bash
docker compose down;
docker rmi ghcr.io/eurofurence/ef-app_backend-dotnet-core:nightly;
rm appsettings.json;
cp src/Eurofurence.App.Server.Web/appsettings.sample.json appsettings.json;
docker compose build;
docker compose up;
```
_Caution:_ This will replace your `appsettings.json` with the default for local development!
> feat(compose): add minio container

- src/Eurofurence.App.Server.Web/Identity/ConfigureOAuth2IntrospectionOptions.cs
Fixes a bug with serializing and deserializing Claims that have been requested from the UserInfo endpoint.
Currently this is done using a ValueTuple, which is incorrectly serialized as an empty json object, and at deserialization causes a `NullReferenceException`.
This PR adds a `CachedClaim` class that is used for serialization instead.
> Bugfix: Fixes serialization and deserialization of cached UserInfo claims

- src/Eurofurence.App.Domain.Model/Knowledge/KnowledgeEntryRecord.cs
- src/Eurofurence.App.Server.Services/Abstractions/ArtistsAlley/TableRegistrationRequest.cs
- src/Eurofurence.App.Server.Services/Abstractions/Fursuits/FursuitBadgeRegistration.cs
- src/Eurofurence.App.Server.Services/Abstractions/Fursuits/IFursuitBadgeService.cs
- src/Eurofurence.App.Server.Services/Abstractions/Images/IImageService.cs
- src/Eurofurence.App.Server.Services/Abstractions/Knowledge/IKnowledgeEntryService.cs
- src/Eurofurence.App.Server.Services/Abstractions/Knowledge/KnowledgeEntryRequest.cs
- src/Eurofurence.App.Server.Services/ArtistsAlley/TableRegistrationService.cs
- src/Eurofurence.App.Server.Services/Fursuits/FursuitBadgeService.cs
- src/Eurofurence.App.Server.Services/Images/ImageService.cs
- src/Eurofurence.App.Server.Services/Knowledge/KnowledgeEntryService.cs
- src/Eurofurence.App.Server.Services/Telegram/AdminConversation.cs
- src/Eurofurence.App.Server.Web/Controllers/ImagesController.cs
- src/Eurofurence.App.Server.Web/Controllers/KnowledgeEntriesController.cs
- src/Eurofurence.App.Server.Web/Jobs/UpdateNewsJob.cs
- src/Eurofurence.App.Tools.CliToolBox/Commands/DealersCommand.cs
- src/Eurofurence.App.Tools.CliToolBox/Commands/ImagesCommand.cs
- src/Eurofurence.App.Tools.CliToolBox/Commands/KnowledgeCommand.cs
- src/Eurofurence.App.Tools.CliToolBox/Commands/MapCommand.cs
- src/Eurofurence.App.Tools.CliToolBox/Commands/StorageCommand.cs
- src/Eurofurence.App.Tools.CliToolBox/Importers/DealersDen/PackageImporter.cs
- src/Eurofurence.App.Tools.CliToolBox/Importers/EventSchedule/ImageImporter.cs
- src/Eurofurence.App.Tools.CliToolBox/Importers/Knowledge/WikIFileImporter.cs
I replaced the old API endpoint which took a byte array as string and replaced it by two API endpoints. A Post endpoint which takes a IFormFile as input and therefore allows file uploads, and a Put endpoint which allows replacing a file with the same id.
**BREAKING CHANGE**: I also changed the fursuit badge registration: Instead of passing a byte array with the image data, an image id is passed. So adding a fursuit badge registration is now a two-step process with first uploading the image using the image endpoint and then passing the image id.
Before: 
```
{
"BadgeNo": 6,
"RegNo": 6,
"Name": "Meta",
"WornBy": "Meta",
"Species": "Protogen",
"Gender": "male",
"ImageContent ": "longByteArrayWithImageData",
"DontPublish": 0,
"CollectionCode": "123"
}
```
After:
```
{
"BadgeNo": 6,
"RegNo": …
```
> BREAKING CHANGE: Reworked image upload, using IFormFile instead of byte arrays

- src/Eurofurence.App.Domain.Model/Knowledge/KnowledgeGroupRecord.cs
- src/Eurofurence.App.Infrastructure.EntityFramework/Migrations/20240629111313_ReplacedFontAwesomeUnicodeByName.Designer.cs
- src/Eurofurence.App.Infrastructure.EntityFramework/Migrations/20240629111313_ReplacedFontAwesomeUnicodeByName.cs
- src/Eurofurence.App.Server.Web/Views/WebPreview/KnowledgeGroupsPreview.cshtml
- src/Eurofurence.App.Tools.CliToolBox/Importers/Knowledge/WikIFileImporter.cs
BREAKING CHANGE: FontAwesomeIconCharacterUnicodeAddress renamed to FontAwesomeIconName. 
It will be filled by the backoffice with the icon name, e.g. "info", instead of the unicode address.
> feat: Using font awesome icon name instead of unicode adress in knowledge base groups

- src/Eurofurence.App.Server.Web/Controllers/KnowledgeEntriesController.cs
- src/Eurofurence.App.Server.Web/Identity/AuthorizationOptions.cs
- src/Eurofurence.App.Server.Web/Identity/RolesClaimsTransformation.cs
- src/Eurofurence.App.Server.Web/Startup.cs
- src/Eurofurence.App.Server.Web/appsettings.sample.json
This PR adds a configurable mapping from IDP groups to backend roles.
Each role in the backend has a list of corresponding IDP groups under the `Authorization` section in the `appsettings.json`.
The groups are mapped, unified and assigned to the claims principal using a claims transformer.
> Configurable Authorization

- src/Eurofurence.App.Domain.Model/Dealers/DealerRecord.cs
- src/Eurofurence.App.Infrastructure.EntityFramework/AppDbContext.cs
- src/Eurofurence.App.Infrastructure.EntityFramework/Migrations/20240718162505_AddedKeywordsToDealers.Designer.cs
- src/Eurofurence.App.Infrastructure.EntityFramework/Migrations/20240718162505_AddedKeywordsToDealers.cs
- src/Eurofurence.App.Server.Services/Dealers/DealerService.cs
- src/Eurofurence.App.Tools.CliToolBox/Importers/DealersDen/PackageImporter.cs
This pull request adds the keywords property to the dealers model.
The categories are now imported from the keys of the keywords.
Also, a few minor issues were fixed in the dealers import and dealer queries.
Example result with the new keywords:
```
"Categories": [
"Commissions and Services",
"Music and Audio",
"Plushies"
],
"Keywords": {
"Commissions and Services": [
"VR Integration",
"Workshops, Classes, Tutorials"
],
"Music and Audio": [
"Music and Audio (Other)"
],
"Plushies": [
"Plushy Animals"
]
},
```
> feat(dealers): expand model by keywords

- Dockerfile
- docker-compose.yml
- src/Eurofurence.App.Backoffice/Components/ImageDialog.razor
- src/Eurofurence.App.Backoffice/Components/KnowledgeEntryDialog.razor
- src/Eurofurence.App.Backoffice/Pages/Images.razor
- src/Eurofurence.App.Backoffice/Pages/KnowledgeBase.razor
- src/Eurofurence.App.Backoffice/Services/IImageService.cs
- src/Eurofurence.App.Backoffice/Services/ImageService.cs
- src/Eurofurence.App.Domain.Model/Images/ImageRecord.cs
- src/Eurofurence.App.Domain.Model/Images/ImageResponse.cs
- src/Eurofurence.App.Domain.Model/Knowledge/KnowledgeEntryResponse.cs
- src/Eurofurence.App.Infrastructure.EntityFramework/AppDbContext.cs
- src/Eurofurence.App.Infrastructure.EntityFramework/Migrations/20240803204301_AddImageUrl.Designer.cs
- src/Eurofurence.App.Infrastructure.EntityFramework/Migrations/20240803204301_AddImageUrl.cs
- src/Eurofurence.App.Server.Services/Abstractions/MinIO/MinIOConfiguration.cs
- src/Eurofurence.App.Server.Services/Images/ImageService.cs
- src/Eurofurence.App.Server.Web/Controllers/ImagesController.cs
- src/Eurofurence.App.Server.Web/Jobs/FlushPrivateMessageNotificationsJob.cs
- src/Eurofurence.App.Server.Web/Jobs/UpdateAnnouncementsJob.cs
- src/Eurofurence.App.Server.Web/Mapper/KnowledgeEntryResponseRegister.cs
- src/Eurofurence.App.Server.Web/appsettings.sample.json
This PR adds a 'Url' property to the images, aswell as a hidden property "InternalFileName" to save the file name under which the file was uploaded to MinIO.
Using the Url property, images can now be loaded from MinIO directly.
The image content endpoints have been set as deprecated.
Loading the images directly from the MinIO url has been implemented to the Backoffice.
> 108 add minio url to image

- src/Eurofurence.App.Server.Services/Abstractions/ArtistsAlley/ITableRegistrationService.cs
- src/Eurofurence.App.Server.Services/ArtistsAlley/TableRegistrationService.cs
- src/Eurofurence.App.Server.Web/Controllers/AnnouncementsController.cs
- src/Eurofurence.App.Server.Web/Controllers/ArtShowController.cs
- src/Eurofurence.App.Server.Web/Controllers/ArtistsAlleyController.cs
- src/Eurofurence.App.Server.Web/Controllers/CommunicationController.cs
- src/Eurofurence.App.Server.Web/Controllers/DealersController.cs
- src/Eurofurence.App.Server.Web/Controllers/EventFeedbackController.cs
- src/Eurofurence.App.Server.Web/Controllers/FursuitsController.cs
- src/Eurofurence.App.Server.Web/Controllers/ImagesController.cs
- src/Eurofurence.App.Server.Web/Controllers/KnowledgeEntriesController.cs
- src/Eurofurence.App.Server.Web/Controllers/KnowledgeGroupsController.cs
- src/Eurofurence.App.Server.Web/Controllers/MapsController.cs
- src/Eurofurence.App.Server.Web/Controllers/PushNotificationsController.cs
- src/Eurofurence.App.Server.Web/Identity/AuthorizationOptions.cs
- src/Eurofurence.App.Server.Web/Identity/RolesClaimsTransformation.cs
- src/Eurofurence.App.Server.Web/appsettings.sample.json
The roles and their access were reworked according to the guideline (see #143).
Also, new API endpoints restricted to Admins were added, for querying a single artist alley table registration and deleting a table registration.
> feat(rbac): rework access roles

- src/Eurofurence.App.Backoffice/Components/KnowledgeEntryDialog.razor
- src/Eurofurence.App.Backoffice/Eurofurence.App.Backoffice.csproj
- src/Eurofurence.App.Backoffice/Pages/KnowledgeBase.razor
I have managed to produce a XSS attack on the knowledgebase site.
It happened when creating new entries, editing and viewing existing ones
When the stored MD code was converted into HTML the output was not sanitized properly and therefore code execution was possible.
This PR should fix this issue at the places I found and sanitizing the HTML output.
> Fixed a XXS vulnerability on the knowledgebase page:

- src/Eurofurence.App.Backoffice/App.razor
- src/Eurofurence.App.Backoffice/Authentication/AuthorizationSettings.cs
- src/Eurofurence.App.Backoffice/Authentication/BackendAccountClaimsFactory.cs
- src/Eurofurence.App.Backoffice/Layout/NavMenu.razor
- src/Eurofurence.App.Backoffice/Pages/DebugClaims.razor
- src/Eurofurence.App.Backoffice/Pages/Home.razor
- src/Eurofurence.App.Backoffice/Pages/Images.razor
- src/Eurofurence.App.Backoffice/Pages/KnowledgeBase.razor
- src/Eurofurence.App.Backoffice/Program.cs
- src/Eurofurence.App.Backoffice/Services/IUsersService.cs
- src/Eurofurence.App.Backoffice/Services/UsersService.cs
- src/Eurofurence.App.Backoffice/wwwroot/appsettings.sample.json
- src/Eurofurence.App.Backoffice/wwwroot/index.html
- src/Eurofurence.App.Domain.Model/Users/UserRecord.cs
- src/Eurofurence.App.Domain.Model/Users/UserRegistration.cs
- src/Eurofurence.App.Domain.Model/Users/UserRegistrationClaims.cs
- src/Eurofurence.App.Domain.Model/Users/UserRegistrationStatus.cs
- src/Eurofurence.App.Server.Web/Controllers/UsersController.cs
- src/Eurofurence.App.Server.Web/Identity/AuthorizationOptions.cs
- src/Eurofurence.App.Server.Web/Identity/RolesClaimsTransformation.cs
> feat(backoffice): require authorization for pages

- Dockerfile
- Dockerfile-backoffice
- justfile
- scripts/import.py
- src/Eurofurence.App.Domain.Model/ArtistsAlley/TableRegistrationRecord.cs
- src/Eurofurence.App.Domain.Model/ArtistsAlley/TableRegistrationRequest.cs
- src/Eurofurence.App.Infrastructure.EntityFramework/AppDbContext.cs
- src/Eurofurence.App.Server.Services/Abstractions/ArtistsAlley/ITableRegistrationService.cs
- src/Eurofurence.App.Server.Services/Abstractions/Images/IImageService.cs
- src/Eurofurence.App.Server.Services/ArtistsAlley/TableRegistrationService.cs
- src/Eurofurence.App.Server.Services/Dealers/DealerService.cs
- src/Eurofurence.App.Server.Services/Events/EventService.cs
- src/Eurofurence.App.Server.Services/Images/ImageService.cs
- src/Eurofurence.App.Server.Services/LostAndFound/LostAndFoundLassieImporter.cs
- src/Eurofurence.App.Server.Web/Controllers/ArtistsAlleyController.cs
- src/Eurofurence.App.Server.Web/Jobs/FlushPrivateMessageNotificationsJob.cs
- src/Eurofurence.App.Server.Web/Jobs/UpdateAnnouncementsJob.cs
- src/Eurofurence.App.Server.Web/Jobs/UpdateDealersJob.cs
- src/Eurofurence.App.Server.Web/Jobs/UpdateEventsJob.cs
- src/Eurofurence.App.Server.Web/Jobs/UpdateFursuitCollectionGameParticipationJob.cs
- src/Eurofurence.App.Server.Web/Jobs/UpdateLostAndFoundJob.cs
* submit image with registration instead of setting image ID
* delete image with deletion of registration
* fix `StateChangeRecords` being stored correctly when auto-rejecting pending registrations upon resubmission
* fix race condition in importers (must not be run in parallel!)
* fix some issues in justfile and import script
* some optimisation attempts for Docker build with caching
> feat(artistalley): submit/delete image with registration

- src/Eurofurence.App.Backoffice/Authentication/BackendAccountClaimsFactory.cs
- src/Eurofurence.App.Backoffice/Authentication/TokenAuthorizationMessageHandler.cs
- src/Eurofurence.App.Backoffice/Layout/RedirectToLogin.razor
- src/Eurofurence.App.Backoffice/Program.cs
- src/Eurofurence.App.Backoffice/Services/IUserService.cs
- src/Eurofurence.App.Backoffice/Services/UserService.cs
- src/Eurofurence.App.Backoffice/wwwroot/index.html
- src/Eurofurence.App.Common/DataDiffUtils/PatchDefinition.cs
This PR fixes a bug where entities were flagged as updated during the imports, although they haven't been changed, which would have caused more loading times for the app.
It also removes the Google font from the Backoffice and fixes errors when the token expires when using the backoffice, now it will redirect to the login instead.
> 168 fix entities being listed as changed due to import

- src/Eurofurence.App.Backoffice/Components/ArtistAlleyApplicationDialog.razor
- src/Eurofurence.App.Backoffice/Components/ConfirmDialog.razor
- src/Eurofurence.App.Backoffice/Layout/MainLayout.razor
- src/Eurofurence.App.Backoffice/Layout/NavMenu.razor
- src/Eurofurence.App.Backoffice/Pages/ArtistAlleyModeration.razor
- src/Eurofurence.App.Backoffice/Pages/Images.razor
- src/Eurofurence.App.Backoffice/Pages/KnowledgeBase.razor
- src/Eurofurence.App.Backoffice/Services/ArtistAlleyService.cs
- src/Eurofurence.App.Backoffice/Services/IArtistAlleyService.cs
- src/Eurofurence.App.Domain.Model/ArtistsAlley/TableRegistrationRecord.cs
- src/Eurofurence.App.Server.Services/ArtistsAlley/TableRegistrationService.cs
- src/Eurofurence.App.Server.Web/Controllers/ArtistsAlleyController.cs
- src/Eurofurence.App.Server.Web/Identity/AuthorizationOptions.cs
- src/Eurofurence.App.Server.Web/Identity/RolesClaimsTransformation.cs
- src/Eurofurence.App.Server.Web/appsettings.sample.json
- test/Eurofurence.App.Server.Services.Tests/Eurofurence.App.Server.Services.Tests.csproj
This PR adds artist alley management to the backoffice, introducing a new API endpoint for setting the artist alley table registration status, aswell as two new access roles, solving #160 .
It also adds a confirm dialog when trying to delete entities.
Thanks to @maakinoh for building the artist alley management :)
> feat(backoffice): manage artist alley registrations (#160)

- src/Eurofurence.App.Domain.Model/PushNotifications/DeviceIdentityRecord.cs
- src/Eurofurence.App.Infrastructure.EntityFramework/Migrations/20240828192551_DeviceIdentityRecordIdentityIdOptional.Designer.cs
- src/Eurofurence.App.Infrastructure.EntityFramework/Migrations/20240828192551_DeviceIdentityRecordIdentityIdOptional.cs
- src/Eurofurence.App.Server.Services/PushNotifications/FirebaseChannelManager.cs
Allows adding device without an IdentityId and re-registering devices under a new IdentityId
> fix(push): Allow registering devices without login and re-registration

- src/Eurofurence.App.Server.Services/Communication/PrivateMessageService.cs
- src/Eurofurence.App.Server.Web/Identity/RolesClaimsTransformation.cs
- src/Eurofurence.App.Server.Web/Startup.cs
Fixes a crash when reading privates messages, by changing how `PrivateMessageService` reads pending private messages and disabling `DBContext` pooling
> fix(pm): fix crash when reading private messages

- src/Eurofurence.App.Server.Web/Identity/RolesClaimsTransformation.cs
The regsys status `checked in` did not get correctly mapped to the enum due to the space, which would likely apply to any other potential similar status in the future (e.g. `partially paid`). Replacing all spaces in returned status to fix this.
> fix(roles): remove spaces from regsys api response

- src/Eurofurence.App.Domain.Model/ArtistsAlley/TableRegistrationRecord.cs
- src/Eurofurence.App.Domain.Model/ArtistsAlley/TableRegistrationRequest.cs
- src/Eurofurence.App.Server.Services/Abstractions/ArtistsAlley/ITableRegistrationService.cs
- src/Eurofurence.App.Server.Services/ArtistsAlley/TableRegistrationService.cs
- src/Eurofurence.App.Server.Web/Controllers/ArtistsAlleyController.cs
* request fields now get properly validated in one place (the service)
* image only gets created/stored if all validations succeed first
* only display name, description, location and image are mandatory
> feat(artistalley): move input validation to service

- src/Eurofurence.App.Domain.Model/Dealers/DealerRecord.cs
* `AttendeeNickname` should only be exposed via `DisplayNameOrAttendeeNickname` if `DisplayName` is not set.
* `RegistrationNumber` should _never_ be exposed.
> fix(dealers): exclude unwanted fields from API

- src/Eurofurence.App.Server.Web/Controllers/DealersController.cs
- src/Eurofurence.App.Server.Web/Eurofurence.App.Server.Web.csproj
- src/Eurofurence.App.Server.Web/Startup.cs
- src/Eurofurence.App.Server.Web/appsettings.sample.json
I moved the Serilog configuration from the startup.cs to the appsettings.json file and added an example configuration to the appsettings.sample.json, that logs with a minimum level of "Information", excluding Microsoft-internal logs, e.g. during API requests, these will only by logged with a loglevel of Warning or higher.
> fix(logging): reduce logging for requests

- src/Eurofurence.App.Backoffice/Components/ArtistAlleyApplicationDialog.razor
- src/Eurofurence.App.Backoffice/Pages/ArtistAlleyModeration.razor
- src/Eurofurence.App.Server.Web/Controllers/ArtistsAlleyController.cs
Artist alley applications can now also be deleted, even if they are already approved or rejected.
I've also fixed an authorization problem in the ArtistAlleyController, in which only admins could retrieve table registrations and change their status
> feat: delete aleady aproved/rejected artist alley applications

- justfile
- src/Eurofurence.App.Backoffice/Layout/MainLayout.razor
- src/Eurofurence.App.Backoffice/Pages/KnowledgeBase.razor
- src/Eurofurence.App.Backoffice/Program.cs
- src/Eurofurence.App.Backoffice/wwwroot/appsettings.sample.json
Knowledge entries are now ordered first by their groups order number and then by their own.
Also, there is now an indicator of the order number in the overview.
> fix: sort knowledge entries by order & show indicator in overview

- src/Eurofurence.App.Domain.Model/Announcements/AnnouncementRequest.cs
- src/Eurofurence.App.Server.Web/Controllers/AnnouncementsController.cs
* POST endpoint required both `Id` and `LastChangeDateTimeUtc` to be set in the request instead of being set server-side.
* Improve error handling to avoid 500 errors with stacktraces.
> fix(announcement): POST required Id and LastChangeDateTimeUtc

- src/Eurofurence.App.Server.Services/Eurofurence.App.Server.Services.csproj
Reverts eurofurence/ef-app_backend-dotnet-core#255
I noticed issues with breaking changes in the new major releases.
We have to adjust our Telegram Bot integration code.
> Revert "build(deps): bump Telegram.Bot and Microsoft.Extensions.Configuration.Binder"

- Dockerfile
- Dockerfile-backoffice
- justfile
- src/Eurofurence.App.Server.Services/Eurofurence.App.Server.Services.csproj
The docker build has been failing recently.
Probably due to several PRs (#242 #250,and #265) - some of which I created myself, to my shame.
+ The Clitoolbox was still referenced at some places
+ Husky.Net wasn't disabled in docker properly.
+ We've updated to dotnet 9 too early, so I rolled back to version 8, since we don't target version 9 yet.
Correct me if I'm wrong here @Metawolve, but AFAIK, you can only compile a dotnet project with the same version of dotnet installed, right?
+ Transitive dependency caused a compile error and I had to upgrade it (no breaking changes from what I'm seeing).
> fix: docker build failed

- src/Eurofurence.App.Server.Services/Abstractions/ArtistsAlley/ITableRegistrationService.cs
- src/Eurofurence.App.Server.Services/ArtistsAlley/TableRegistrationService.cs
- src/Eurofurence.App.Server.Web/Controllers/ArtistsAlleyController.cs
Closes: #286 
This PR adds a new API endpoint for deleting the currently logged-in user's artist alley registration.
> feat(#286): add new API endpoint for deleting the user's own artist alley registration

- src/Eurofurence.App.Backoffice/Program.cs
Just. a small one line fix to make Sentry also configure from the `appsettings.json` in the Blazor/Backoffice Project, like it should.
> Configure SentryBlazorOptions using appsettings.json

- src/Eurofurence.App.Backoffice/Eurofurence.App.Backoffice.csproj
- src/Eurofurence.App.Server.Services/Abstractions/ArtistsAlley/ITableRegistrationService.cs
- src/Eurofurence.App.Server.Services/Abstractions/Telegram/ITelegramMessageSender.cs
- src/Eurofurence.App.Server.Services/ArtistsAlley/TableRegistrationService.cs
- src/Eurofurence.App.Server.Services/Telegram/TelegramMessageBroker.cs
- src/Eurofurence.App.Server.Web/Controllers/ArtistsAlleyController.cs
- src/Eurofurence.App.Server.Web/Telegram/BotService.cs
Closes: #329 
Also Microsoft.AspNetCore.Components.WebAssembly.DevServer was downgraded to fix a bug when starting the backoffice without Docker.
Furthermore, when approving a table reg, the database changes are persisted **before** the telegram messages are sent.
This could also be moved to a separate issue/PR if you like.
> fix(#329): sending an artist alley table registration request now results in an update of the existing data

- src/Eurofurence.App.Server.Services/Knowledge/KnowledgeEntryService.cs
Fixed a bug where non-published knowledge base entries would show up in the sync endpoint response
> fix(knowledge): non-published entries in sync endpoint
